# Generated by Django 2.2.5 on 2019-09-19 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='membership_type',
            field=models.CharField(choices=[('Professional', 'pro'), ('Enterprise', 'ent'), ('Free', 'free')], default='Free', max_length=30),
        ),
    ]
