# Generated by Django 4.2.2 on 2023-07-22 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('user_id', models.IntegerField()),
                ('tier', models.CharField(max_length=10)),
                ('amount_cad', models.IntegerField()),
                ('amount_fx', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fx_choice', models.IntegerField()),
                ('order_time', models.DateTimeField()),
                ('card_last_6', models.IntegerField(max_length=6)),
                ('result', models.BooleanField()),
            ],
        ),
    ]
