# Generated by Django 4.2.2 on 2023-07-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_order'),
        ('users', '0003_auto_20190919_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='club',
            field=models.ManyToManyField(to='club.club'),
        ),
    ]
