# Generated by Django 4.2.2 on 2023-07-24 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_order'),
        ('users', '0004_profile_club'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='club',
        ),
        migrations.AddField(
            model_name='profile',
            name='club',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='club.club'),
        ),
    ]
