# Generated by Django 4.2.2 on 2023-07-23 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_auto_20190919_2250'),
        ('courses', '0003_auto_20190918_2245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='course',
            name='allowed_memberships',
            field=models.ManyToManyField(related_name='memberships_allowed', to='memberships.membership'),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.category'),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(help_text='Please use the following formats: 1 Week or 1 Month', max_length=10),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='courses.course'),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('title', 'course')},
        ),
    ]
