# Generated by Django 4.2.2 on 2023-07-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_remove_course_club_course_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='student_count',
            field=models.IntegerField(default=0),
        ),
    ]
