# Generated by Django 4.2.2 on 2023-06-11 03:07

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Buyer",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shipping_address",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "area",
                    models.CharField(
                        choices=[
                            ("W", "Windsor"),
                            ("LS", "LaSalle"),
                            ("A", "Amherstburg"),
                            ("L", "Lakeshore"),
                            ("LE", "Leamington"),
                            ("C", "Chatham"),
                            ("T", "Toronto"),
                            ("WL", "Waterloo"),
                        ],
                        default="C",
                        max_length=2,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            bases=("auth.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="CarType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="GroupMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=20)),
                ("last_name", models.CharField(max_length=20)),
                ("semester", models.CharField(max_length=20)),
                ("link", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("car_name", models.CharField(max_length=200)),
                ("car_price", models.DecimalField(decimal_places=6, max_digits=10)),
                ("inventory", models.PositiveIntegerField(default=10)),
                ("instock", models.BooleanField(default=True)),
                (
                    "car_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to="carapp.cartype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderVehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "cancelled"),
                            (1, "placed"),
                            (2, "shipped"),
                            (3, "delivered"),
                        ]
                    ),
                ),
                ("updated_at", models.DateField(auto_now=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="carapp.buyer"
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="carapp.vehicle"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="buyer",
            name="interested_in",
            field=models.ManyToManyField(to="carapp.cartype"),
        ),
    ]
