# Generated by Django 4.2.2 on 2023-06-11 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="groupmember",
            options={"ordering": ["first_name"]},
        ),
        migrations.AlterField(
            model_name="groupmember",
            name="semester",
            field=models.IntegerField(),
        ),
    ]
